const BOARD_CONTENT_REQUEST = 'BOARD_CONTENT_REQUEST';
const BOARD_CONTENT_SUCCESS = 'BOARD_CONTENT_SUCCESS';
const BOARD_CONTENT_ERROR ='BOARD_CONTENT_ERROR';

export {
    BOARD_CONTENT_REQUEST,
    BOARD_CONTENT_SUCCESS,
    BOARD_CONTENT_ERROR
}

