const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_REQUEST_PERSONAL = "REGISTER_REQUEST_PERSONAL";
const REGISTER_REQUEST_BUSINESS = "REGISTER_REQUEST_BUSINESS";
const REGISTER_ERROR = "REGISTER_ERROR";

export {
    REGISTER_SUCCESS,
    REGISTER_REQUEST_PERSONAL,
    REGISTER_REQUEST_BUSINESS,
    REGISTER_ERROR
}