const SHIPPING_REQUEST = "SHIPPING_REQUEST";
const SHIPPING_SUCCESS = "SHIPPING_SUCCESS";
const SHIPPING_ERROR = "SHIPPING_ERROR";
const SHIPPING_LIST_REQUEST = "SHIPPING_LIST_REQUEST";
const SHIPPING_LIST_SUCCESS = "SHIPPING_LIST_SUCCESS";
const SHIPPING_LIST_ERROR = "SHIPPING_LIST_ERROR";
const SHIPPING_ADD_LIST = "SHIPPING_ADD_LIST";
const SHIPPING_DELETE_LIST = "SHIPPING_DELETE_LIST";
const SHIPPING_UPDATE_LIST = "SHIPPING_UPDATE_LIST";


export {
    SHIPPING_REQUEST,
    SHIPPING_SUCCESS,
    SHIPPING_ERROR,
    SHIPPING_LIST_REQUEST,
    SHIPPING_LIST_SUCCESS,
    SHIPPING_LIST_ERROR,
    SHIPPING_ADD_LIST,
    SHIPPING_DELETE_LIST,
    SHIPPING_UPDATE_LIST,
}