const LOGIN= 'LOGIN' ;
const LOGIN_SUCCESS= 'LOGIN_SUCCESS' ;
const LOGIN_ERROR = 'LOGIN_ERROR';
const LOGOUT= 'LOGOUT';
const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS';
const LOGOUT_ERROR = 'LOGOUT_ERROR';

export {
    LOGIN,
    LOGOUT,
    LOGIN_SUCCESS,
    LOGOUT_SUCCESS,
    LOGIN_ERROR,
    LOGOUT_ERROR
};

