const FILE_REQUEST = "FILE_REQUEST";
const FILE_SENT_SUCCESS = "FILE_SENT_SUCCESS";
const FILE_SENT_ERROR = "FILE_SENT_ERROR";
const FILE_NAME_REQUEST = "FILE_NAME_GET";
const FILE_NAME_SUCCESS = "FILE_NAME_SUCCESS";
const FILE_NAME_ERROR = "FILE_NAME_ERROR";

export {
    FILE_REQUEST,
    FILE_SENT_SUCCESS,
    FILE_SENT_ERROR,
    FILE_NAME_REQUEST,
    FILE_NAME_SUCCESS,
    FILE_NAME_ERROR,
}