const USER_REQUEST = "USER_REQUEST";
const USER_SUCCESS = "USER_SUCCESS";
const USER_ERROR = "USER_ERROR";
const USER_UPDATE = "USER_UPDATE";
const USER_DELETE = "USER_DELETE";

export {
    USER_REQUEST,
    USER_SUCCESS,
    USER_ERROR,
    USER_UPDATE,
    USER_DELETE,
}