const CART_REQUEST = "CART_REQUEST";
const CART_SUCCESS = "CART_SUCCESS";
const CART_ERROR = "CART_ERROR";
const ADD_ITEM ="ADD_ITEM";
const REMOVE_ITEM = "REMOVE_ITEM";
const GET_CART = "GET_CART";
const INCREASE_ITEM_QTY = "INCREASE_ITEM_QTY";
const DECREASE_ITEM_QTY = "DECREASE_ITEM_QTY";


export {
    CART_REQUEST,
    CART_SUCCESS,
    CART_ERROR,
    ADD_ITEM,
    REMOVE_ITEM,
    GET_CART,
    INCREASE_ITEM_QTY,
    DECREASE_ITEM_QTY,
}