
const GET_BINDING = "GET_BINDING";
const GET_BINDING_SUCCESS = "GET_BINDING_SUCCESS";
const GET_BINDING_ERROR = "GET_BINDING_ERROR";

const GET_DOCU_SPEC = "GET_DOCU_SPEC";
const GET_DOCU_SPEC_SUCCESS = "GET_DOCU_SPEC_SUCCESS";
const GET_DOCU_SPEC_ERROR = "GET_DOCU_SPEC_ERROR";

const GET_PAGE_OPTION = "GET_PAGE_OPTION";
const GET_PAGE_OPTION_SUCCESS = "GET_PAGE_OPTION_SUCCESS";
const GET_PAGE_OPTION_ERROR = "GET_PAGE_OPTION_ERROR";

const GET_PROCESS = "GET_PROCESS";
const GET_PROCESS_SUCCESS = "GET_PROCESS_SUCCESS";
const GET_PROCESS_ERROR = "GET_PROCESS_ERROR";

const GET_PROCESS_INFO_LIST = "GET_PROCESS_INFO_LIST";
const GET_PROCESS_INFO_LIST_SUCCESS = "GET_PROCESS_INFO_LIST_SUCCESS";
const GET_PROCESS_INFO_LIST_ERROR = "GET_PROCESS_INFO_LIST_ERROR";

const GET_SLIP_TYPE ="GET_SLIP_TYPE";
const GET_SLIP_TYPE_SUCCESS = "GET_SLIP_TYPE_SUCCESS";
const GET_SLIP_TYPE_ERROR ="GET_SLIP_TYPE_ERROR";

export {
    GET_BINDING,
    GET_BINDING_SUCCESS,
    GET_BINDING_ERROR,

    GET_DOCU_SPEC,
    GET_DOCU_SPEC_SUCCESS,
    GET_DOCU_SPEC_ERROR,

    GET_PAGE_OPTION,
    GET_PAGE_OPTION_SUCCESS,
    GET_PAGE_OPTION_ERROR,

    GET_PROCESS,
    GET_PROCESS_SUCCESS,
    GET_PROCESS_ERROR,

    GET_PROCESS_INFO_LIST,
    GET_PROCESS_INFO_LIST_SUCCESS,
    GET_PROCESS_INFO_LIST_ERROR,

    GET_SLIP_TYPE,
    GET_SLIP_TYPE_SUCCESS,
    GET_SLIP_TYPE_ERROR,

}