

const GET_LARGECATEGORY_ADMIN = "GET_LARGECATEGORY_ADMIN";
const GET_LARGECATEGORY_SUCCESS = "GET_LARGECATEGORY_SUCCESS";
const GET_LARGECATEGORY_ERROR = "GET_LARGECATEGORY_ERROR";

const SAVE_LARGECATEGORY_ADMIN = "SAVE_LARGECATEGORY_ADMIN";
const SAVE_LARGECATEGORY_SUCCESS = "SAVE_LARGECATEGORY_SUCCESS";
const SAVE_LARGECATEGORY_ERROR = "SAVE_LARGECATEGORY_ERROR";

const GET_MIDIUMCATEGORY_ADMIN = "GET_MIDIUMCATEGORY_ADMIN";
const GET_MIDIUMCATEGORY_SUCCESS = "GET_MIDIUMCATEGORY_SUCCESS";
const GET_MIDIUMCATEGORY_ERROR = "GET_MIDIUMCATEGORY_ERROR";

const SAVE_MIDIUMCATEGORY_ADMIN = "SAVE_MIDIUMCATEGORY_ADMIN";
const SAVE_MIDIUMCATEGORY_SUCCESS = "SAVE_MIDIUMCATEGORY_SUCCESS";
const SAVE_MIDIUMCATEGORY_ERROR = "SAVE_MIDIUMCATEGORY_ERROR";

const DELETE_LARGECATEGORY_ADMIN = "DELETE_LARGECATEGORY_ADMIN";
const UPDATE_LARGECATRGORY_ADMIN = "UPDATE_LARGECATEGORY_ADMIN";

const DELETE_MIDIUMCATEGORY_ADMIN = "DELETE_MIDIUMCATEGORY_ADMIN";
const UPDATE_MIDIUMCATEGORY_ADMIN = "UPDATE_MIDIUMCATEGORY_ADMIN";
export {
    GET_LARGECATEGORY_ADMIN,
    GET_LARGECATEGORY_SUCCESS,
    GET_LARGECATEGORY_ERROR,

    SAVE_LARGECATEGORY_ADMIN,
    SAVE_LARGECATEGORY_SUCCESS,
    SAVE_LARGECATEGORY_ERROR,
    
    GET_MIDIUMCATEGORY_ADMIN,
    GET_MIDIUMCATEGORY_SUCCESS,
    GET_MIDIUMCATEGORY_ERROR,

    SAVE_MIDIUMCATEGORY_ADMIN,
    SAVE_MIDIUMCATEGORY_SUCCESS,
    SAVE_MIDIUMCATEGORY_ERROR,

    DELETE_LARGECATEGORY_ADMIN,
    UPDATE_LARGECATRGORY_ADMIN,

    DELETE_MIDIUMCATEGORY_ADMIN,
    UPDATE_MIDIUMCATEGORY_ADMIN
}