const GET_ADMIN_PRODUCT = "GET_ADMIN_PRODUCT";
const GET_ADMIN_PRODUCT_SUCCESS = "GET_ADMIN_PRODUCT_SUCCESS";
const GET_ADMIN_PRODUCT_ERROR = "GET_ADMIN_PRODUCT_ERROR";

const GET_ADMIN_ONE_PRODUCT = "GET_ADMIN_ONE_PRODUCT";
const GET_ADMIN_ONE_PRODUCT_SUCCESS = "GET_ADMIN_ONE_PRODUCT_SUCCESS";
const GET_ADMIN_ONE_PRODUCT_ERROR = "GET_ADMIN_ONE_PRODUCT_ERROR";

const GET_ADMIN_QUANTITY = "GET_ADMIN_QUANTITY";
const GET_ADMIN_QUANTITY_SUCCESS = "GET_ADMIN_QUANTITY_SUCCESS";
const GET_ADMIN_QUANTITY_ERROR = "GET_ADMIN_QUANTITY_ERROR";

const GET_ADMIN_UNIT ="GET_ADMIN_UNIT";
const GET_ADMIN_UNIT_SUCCESS="GET_ADMIN_UNIT_SUCCESS";
const GET_ADMIN_UNIT_ERROR="GET_ADMIN_UNIT_ERROR";

const GET_ADMIN_BINDING = "GET_ADMIN_BINDING";
const GET_ADMIN_BINDING_SUCCESS = "GET_ADMIN_BINDING_SUCCESS";
const GET_ADMIN_BINDING_ERROR = "GET_ADMIN_BINDING_ERROR";

const GET_ADMIN_PAPER = "GET_ADMIN_PAPER";
const GET_ADMIN_PAPER_SUCCESS = "GET_ADMIN_PAPER_SUCCESS";
const GET_ADMIN_PAPER_ERROR = "GET_ADMIN_PAPER_ERROR";

const GET_ADMIN_DOCUSPEC = "GET_ADMIN_DOCUSPEC";
const GET_ADMIN_DOCUSPEC_SUCCESS ="GET_ADMIN_DOCUSPEC_SUCCESS";
const GET_ADMIN_DOCUSPEC_ERROR = "GET_ADMIN_DOCUSPEC_ERROR";

const GET_ADMIN_PAGEOPTION = "GET_ADMIN_PAGEOPTION";
const GET_ADMIN_PAGEOPTION_SUCCESS = "GET_ADMIN_PAGEOPTION_SUCCESS";
const GET_ADMIN_PAGEOPTION_ERROR = "GET_ADMIN_PAGEOPTION_ERROR";

const GET_ADMIN_POSTPROCESS = "GET_ADMIN_POSTPROCESS";
const GET_ADMIN_POSTPROCESS_SUCCESS = "GET_ADMIN_POSTPROCESS_SUCCESS";
const GET_ADMIN_POSTPROCESS_ERROR = "GET_ADMIN_POSTPROCESS_ERROR";

const GET_ADMIN_ONE_PRODUCT_PROCESSDETAIL = "GET_ADMIN_ONE_PRODUCT_PROCESSDETAIL"

const CREATE_ADMIN_PRODUCT = "CREATE_ADMIN_PRODUCT";
const DELETE_ADMIN_PRODUCT = "DELETE_ADMIN_PRODUCT";
const UPDATE_ADMIN_PRODUCT = "UPDATE_ADMIN_PRODUCT";

const CREATE_ADMIN_BINDING = "CREATE_ADMIN_BINDING";
const CREATE_ADMIN_BINDING_SUCCESS = "CREATE_ADMIN_BINDING_SUCCESS";
const DELETE_ADMIN_BINDING = "DELETE_ADMIN_BINDING";
const UPDATE_ADMIN_BINDING = "UPDATE_ADMIN_BINDING";
const SELECT_ADMIN_BINDING = "SELECT_ADMIN_BINDING";

const SELECT_ADMIN_DOCUSPEC = "SELECT_ADMIN_DOCUSPEC";
const CREATE_ADMIN_DOCUSPEC = "CREATE_ADMIN_DOCUSPEC";
const CREATE_ADMIN_DOCUSPEC_SUCCESS = "CREATE_ADMIN_DOCUSPEC_SUCCESS";
const DELETE_ADMIN_DOCUSPEC = "DELETE_ADMIN_DOCUSPEC";
const UPDATE_ADMIN_DOCUSPEC = "UPDATE_ADMIN_DOCUSPEC";

const CREATE_ADMIN_QUANTITY = "CREATE_ADMIN_QUANTITY";
const CREATE_ADMIN_QUANTITY_SUCCESS = "CREATE_ADMIN_QUANTITY_SUCCESS";
const DELETE_ADMIN_QUANTITY = "DELETE_ADMIN_QUANTITY";
const UPDATE_ADMIN_QUANTITY = "UPDATE_ADMIN_QUANTITY";
const SELECT_ADMIN_QUANTITY = "SELECT_ADMIN_QUANTITY";

const SELECT_ADMIN_PAPER = "SELECT_ADMIN_PAPER";
const CREATE_ADMIN_PAPER = "CREATE_ADMIN_PAPER";
const CREATE_ADMIN_PAPER_SUCCESS = "CREATE_ADMIN_PAPER_SUCCESS";
const DELETE_ADMIN_PAPER = "DELETE_ADMIN_PAPER";
const UPDATE_ADMIN_PAPER = "UPDATE_ADMIN_PAPER";

const SELECT_ADMIN_PAGEOPTION = "SELECT_ADMIN_PAGEOPTION";
const CREATE_ADMIN_PAGEOPTION = "CREATE_ADMIN_PAGEOPTION";
const CREATE_ADMIN_PAGEOPTION_SUCCESS = "CREATE_ADMIN_PAGEOPTION_SUCCESS";
const DELETE_ADMIN_PAGEOPTION = "DELETE_ADMIN_PAGEOPTION";
const UPDATE_ADMIN_PAGEOPTION = "UPDATE_ADMIN_PAGEOPTION";

const SELECT_ADMIN_POSTPROCESS = "SELECT_ADMIN_POSTPROCESS";
const CREATE_ADMIN_POSTPROCESS = "CREATE_ADMIN_POSTPROCESS";
const CREATE_ADMIN_POSTPROCESS_SUCCESS = "CREATE_ADMIN_POSTPROCESS_SUCCESS";
const DELETE_ADMIN_POSTPROCESS = "DELETE_ADMIN_POSTPROCESS";
const UPDATE_ADMIN_POSTPROCESS = "UPDATE_ADMIN_POSTPROCESS";

const CREATE_ADMIN_POSTPROCESS_DETAIL = "CREATE_ADMIN_POSTPROCESS_DETAIL";
const DELETE_ADMIN_POSTPROCESS_DETAIL = "DELETE_ADMIN_POSTPROCESS_DETAIL";
const UPDATE_ADMIN_POSTPROCESS_DETAIL = "UPDATE_ADMIN_POSTPROCESS_DETAIL";

const SELECT_ADMIN_OFFSET = "SELECT_ADMIN_OFFSET";

const GET_ADMIN_PRINTMETHOD = "GET_ADMIN_PRINTMETHOD";
const GET_ADMIN_PRINTMETHOD_SUCCESS = "GET_ADMIN_PRINTMETHOD_SUCCESS";
const GET_ADMIN_PRINTMETHOD_ERROR = "GET_ADMIN_PRINTMETHOD_ERROR";

const CREARE_ADMIN_PRINTMETHOD = "CREARE_ADMIN_PRINTMETHOD";
const UPDATE_ADMIN_PRINTMETHOD = "UPDATE_ADMIN_PRINTMETHOD";
const DELETE_ADMIN_PRINTMETHOD = "DELETE_ADMIN_PRINTMETHOD";

export {
    GET_ADMIN_PRODUCT,
    GET_ADMIN_PRODUCT_SUCCESS,
    GET_ADMIN_PRODUCT_ERROR,

    GET_ADMIN_ONE_PRODUCT,
    GET_ADMIN_ONE_PRODUCT_SUCCESS,
    GET_ADMIN_ONE_PRODUCT_ERROR,

    GET_ADMIN_QUANTITY,
    GET_ADMIN_QUANTITY_SUCCESS,
    GET_ADMIN_QUANTITY_ERROR,

    GET_ADMIN_BINDING,
    GET_ADMIN_BINDING_SUCCESS,
    GET_ADMIN_BINDING_ERROR,

    GET_ADMIN_PAPER,
    GET_ADMIN_PAPER_SUCCESS,
    GET_ADMIN_PAPER_ERROR,

    GET_ADMIN_PAGEOPTION,
    GET_ADMIN_PAGEOPTION_SUCCESS,
    GET_ADMIN_PAGEOPTION_ERROR,

    GET_ADMIN_DOCUSPEC,
    GET_ADMIN_DOCUSPEC_SUCCESS,
    GET_ADMIN_DOCUSPEC_ERROR,

    GET_ADMIN_POSTPROCESS,
    GET_ADMIN_POSTPROCESS_SUCCESS,
    GET_ADMIN_POSTPROCESS_ERROR,

    GET_ADMIN_UNIT,
    GET_ADMIN_UNIT_SUCCESS,
    GET_ADMIN_UNIT_ERROR,

    GET_ADMIN_ONE_PRODUCT_PROCESSDETAIL,

    CREATE_ADMIN_PRODUCT,
    DELETE_ADMIN_PRODUCT,
    UPDATE_ADMIN_PRODUCT,

    CREATE_ADMIN_BINDING,
    CREATE_ADMIN_BINDING_SUCCESS,
    DELETE_ADMIN_BINDING,
    UPDATE_ADMIN_BINDING,
    SELECT_ADMIN_BINDING,

    CREATE_ADMIN_DOCUSPEC,
    CREATE_ADMIN_DOCUSPEC_SUCCESS,
    DELETE_ADMIN_DOCUSPEC,
    UPDATE_ADMIN_DOCUSPEC,
    SELECT_ADMIN_DOCUSPEC,

    CREATE_ADMIN_QUANTITY,
    CREATE_ADMIN_QUANTITY_SUCCESS,
    DELETE_ADMIN_QUANTITY,
    UPDATE_ADMIN_QUANTITY,
    SELECT_ADMIN_QUANTITY,

    CREATE_ADMIN_PAPER,
    CREATE_ADMIN_PAPER_SUCCESS,
    DELETE_ADMIN_PAPER,
    UPDATE_ADMIN_PAPER,
    SELECT_ADMIN_PAPER,
    
    CREATE_ADMIN_PAGEOPTION,
    CREATE_ADMIN_PAGEOPTION_SUCCESS,
    DELETE_ADMIN_PAGEOPTION,
    UPDATE_ADMIN_PAGEOPTION,
    SELECT_ADMIN_PAGEOPTION,

    CREATE_ADMIN_POSTPROCESS,
    CREATE_ADMIN_POSTPROCESS_SUCCESS,
    DELETE_ADMIN_POSTPROCESS,
    UPDATE_ADMIN_POSTPROCESS,
    SELECT_ADMIN_POSTPROCESS,

    CREATE_ADMIN_POSTPROCESS_DETAIL,
    DELETE_ADMIN_POSTPROCESS_DETAIL,
    UPDATE_ADMIN_POSTPROCESS_DETAIL,

    SELECT_ADMIN_OFFSET,

    GET_ADMIN_PRINTMETHOD,
    GET_ADMIN_PRINTMETHOD_SUCCESS,
    GET_ADMIN_PRINTMETHOD_ERROR,

    CREARE_ADMIN_PRINTMETHOD,
    UPDATE_ADMIN_PRINTMETHOD,
    DELETE_ADMIN_PRINTMETHOD
}
